spring:
  application:
    name: demo
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/zhidao?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123123123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8082
